# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b7737d6b3fead086797df7c1dc5efef6e6845f26038c8bc928e8c68b5f458fcedea24257475b1097b3b54fe1eda417ce93a66cf4fbf970753b1b4257ec9077f

test:
  secret_key_base: f7b086e0c410745eb9ef01b806e892086e41855897aeb037c3787b52869e8ca1cc552850453efa8506638c990f3dba958fc3dd664ad92b0352ca81810e14edaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
